version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.24.2
    - 5.34.0
    - 5.35.1
    - 5.36.0
  - dependency-name: elastic-apm-node
    versions:
    - 3.10.0
    - 3.11.0
    - 3.12.0
    - 3.12.1
    - 3.13.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.1
    - 4.8.1
  - dependency-name: express-fileupload
    versions:
    - 1.1.9
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
