version: '3.1'
services:
  gtms-testing-queue:
    image: rabbitmq:3
    expose:
      - 5672
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: localhost 
      QUEUE_HOST: gtms-testing-queue
      APP_DOMAIN: testing
      VERSION: dev
    # command: ["./scripts/wait-for-it.sh", "gtms-testing-queue:5672", "--", "yarn", "workspaces", "run", "test"]
    command: ["yarn", "workspace", "@gtms/service-auth", "test"]
    depends_on:
      - gtms-testing-queue
