version: '3.3'
services:
  gtms-dev-queue:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 8080:15672
    volumes:
      - ./devFiles/rabbitmq-data/:/var/lib/rabbitmq/
  gtms-dev-mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./devFiles/mongo-data/:/data/db
  gtms-dev-mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=gtms-dev-mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - 8081:8081
