env = "qa-stable"
docker_host = "tcp://192.168.0.33:2376/"
queue_host = "rabbitmq-qa-stable"
S3_BUCKET = "gtms-files-qa-stable"
AWS_ENDPOINT = "s3.nl-ams.scw.cloud"
AWS_REGION = "nl-ams"
db_name = "gtms"
